CREATE TABLE DEPARTMENT (
    DM_ID   INT PRIMARY KEY, 
    DM_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE LECTUREROOM (
    LR_ID   INT PRIMARY KEY, 
    LR_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE STUDENT (
    ST_ID   INT PRIMARY KEY, 
    ST_NAME VARCHAR(100) NOT NULL, 
    ST_TEL  VARCHAR(20), 
    ST_PW   VARCHAR(255) NOT NULL, 
    DM_ID   INT, 
    FOREIGN KEY (DM_ID) REFERENCES DEPARTMENT(DM_ID)
);

CREATE TABLE PROFESSOR (
    PF_ID   INT PRIMARY KEY, 
    PF_SUB  VARCHAR(100) NOT NULL, 
    PF_NAME VARCHAR(100) NOT NULL, 
    PF_PW   VARCHAR(255) NOT NULL, 
    PF_TEL  VARCHAR(20), 
    DM_ID   INT, 
    FOREIGN KEY (DM_ID) REFERENCES DEPARTMENT(DM_ID)
);

CREATE TABLE SUBJECT (
    SJ_ID      INT PRIMARY KEY, 
    SJ_NAME    VARCHAR(100) NOT NULL, 
    SJ_TIME    VARCHAR(50) NOT NULL, 
    PF_ID      INT, 
    LR_ID      INT, 
    MAX_PEOPLE INT NOT NULL, 
    FOREIGN KEY (PF_ID) REFERENCES PROFESSOR(PF_ID),
    FOREIGN KEY (LR_ID) REFERENCES LECTUREROOM(LR_ID)
);

CREATE TABLE SIGNUP (
    SIGNUP_ID INT PRIMARY KEY, 
    SJ_ID     INT, 
    ST_ID     INT, 
    DM_ID     INT, 
    FOREIGN KEY (SJ_ID) REFERENCES SUBJECT(SJ_ID),
    FOREIGN KEY (ST_ID) REFERENCES STUDENT(ST_ID),
    FOREIGN KEY (DM_ID) REFERENCES DEPARTMENT(DM_ID)
);
